### ISSUE TITLE
Do not allow multiple accounts with same IP address

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#19]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

An option to block users with vpn, and a limit for accounts at one ip adress.

### Describe the solution you'd like.

Block users from accessing the site with vpn and alts

### Additional context to this request.

ALT - alternative account

**Comment by liechtenberg** [comment]
There's no way you can efficiently block VPN ISPs/IPs. If big corporations can't manage to do it smoothly, this surely can't.

**Comment by camwhi-te** [comment]
Agreed with @sybetjeh. While I can definitely implement a solution which does not allow multiple accounts with the same IP, there's essentially no way of consistently and efficiently blocking VPN connections.

**Comment by OlekAleksander** [comment]
There are some APIs that work well, but on most of them theres a limit for requests

**Comment by DemonMartin** [comment]
I can recommend iphub.info, they have a daily request limit of 1k IPs (free), adding a System which Caches an IP for X (configurable) hours/days etc. would make the request amount even less :)

**Comment by liechtenberg** [comment]
Well, limiting 1 account per idea is a good start. But I personally wouldn't like it if my IP is being sent to a third-party API just to combat alt-accounts. Free hosting (or something along this lines) will **always** have this issue, you'll need to deal with this

**Comment by liechtenberg** [comment]
You could also use cache/cookies and see if they've made an account, but this also can be easily bypassed

**Comment by DemonMartin** [comment]
Well it‘s possible to be set as a setting, but only check on registration/login and once it‘s enabled it can display a warning that once you login/register it will tell that your IP is being sent to a 3rd-Party

**Comment by liechtenberg** [comment]
Yes, but it's just less secure relying on a third-party vendor. If they have a databreach, your data is exposed and you'll need to explain it to your clients on their behalf. Not practical just because you wanna combat alternative accounts. Honestly just check accounts manually and decide for yourself it's an alt or not. Might be slower but more effective if a human does it

**Comment by liechtenberg** [comment]
And if the third-party goes offline, your login/register page will be useless

**Comment by DemonMartin** [comment]
Verifying the account by hand is not only ineffective but next to impossible on a larger scale.  If it goes offline it's not your fault as you don't own it, that's why I said before login it should say that a third party service is used.  If it goes offline, the setting can be disabled while offline.  Since only the IPs are compared and not stored in the database, we wouldn't have to worry about a data breach either.

**Comment by liechtenberg** [comment]
I didn't mean verifying it on hand. I meant you check out accounts that you find yourself suspicious.. There's no way you can block VPNs, it's just not happening even with APIs.

**Comment by liechtenberg** [comment]
You also don't know what happens with it. They obviously do store IPs that are "potential" VPNs. Imagine if you get falsely flagged on it. Good luck getting that resolved 👀

**Comment by camwhi-te** [comment]
While Jexactyl may support the option to forbid multiple accounts being linked to the same IP address, I will **not** be introducing a third-party service in order to prevent VPN connections - it would lead to a lot of hassle and extra configuration which just isn't worth it. If you wish to use an external service to check for VPN's, you're free to modify the panel to your liking.

**Comment by TheFallenSpirit** [comment]
Effectively I do not think this is a good idea. Trying to implement a solution like this is a big hassle as there will be many issues related to bypasses and glitches in the system. If this were to be implemented people would just VPN. And to stop people from using a VPN would be a living **nightmare**. If you want to stop botting then introducing a global threshold to stop x amount of accounts from being created in x amount of time would be better. IP banning is practically useless at this stage of the internet.

**Comment by camwhi-te** [comment]
This has already been implemented, but I'm keeping this open as I need to add a toggle for it admin-side. People have been running into issues with proxies, so there needs to be an option for it.

**Comment by camwhi-te** [comment]
Resolved in 3026696f2d7c0e341b12d306a4eb2e269825b74b
