### ISSUE TITLE
More payment methods or add custom payment options from the admin panel.

### ISSUE THREAD

**Issue by r4club** [Jexactyl/Jexactyl#228]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

You can add payment methods like revolut or bank transfers or better adding the custom payment method option in the admin panel then the users will choose which custom payment method they will pay with, the payment method information will be displayed on a separate page and then on the panel page they will click a button that they have successfully paid or button that they failed to pay by clicking this button a message will be sent by email or in the admin panel that they have paid or failed to pay from there the plan is pending and the admin decides whether to activate their plan or not.

### Additional context to this request.

No really. I think it's very good idea and necessary for international big or small business companies in the world.

**Comment by camwhi-te** [comment]
Not looking into this due to the following reason(s):
- This Panel is meant to have a *simple* billing system, not a WHMCS/Blesta ripoff
- Stripe and PayPal fill 95% of the demand that there is for said billing system
- Payment approval may be a thing in the future
- Dealing with card information directly on the Panel is 100% not something I am comfortable with implementing, as admins could steal customer banking information if they manipulate the code to not hash/hide certain information.
